---
language: python
services: docker

matrix:
  include:
    - os: linux
      dist: xenial

before_script:
  - cd ../
  - mv ansible-role-deploy-blackbox-exporter deploy-blackbox-exporter
  - cd deploy-blackbox-exporter

install:
  - pip install molecule docker

script:
  - molecule lint
