---

- name: Check variables are defined
  assert:
    that:
      - "blackbox_exporter_release_version is defined"
      - "blackbox_exporter_user is defined"
      - "blackbox_exporter_group is defined"
      - "blackbox_config_dir is defined"

- name: Get the Blackbox Exporter release version from GitHub
  uri:
    url: https://api.github.com/repos/prometheus/blackbox_exporter/releases/{{ blackbox_exporter_release_version }}
    return_content: true
    status_code: 200
    body_format: json
  register: blackbox_exporter_release

- name: Get Blackbox Exporter version
  set_fact:
    blackbox_exporter_version: "{{ blackbox_exporter_release.json.tag_name }}"
    blackbox_exporter_version_number: "{{ blackbox_exporter_release.json.tag_name[1:] }}"

- name: Create the Blackbox group
  group:
    name: "{{ blackbox_exporter_group }}"

- name: Create the Blackbox Exporter user
  user:
    name: "{{ blackbox_exporter_user }}"
    create_home: false
    shell: /bin/false
    group: "{{ blackbox_exporter_group }}"

- name: Install Blackbox Exporter
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version_number }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy Blackbox Exporter file to bin
  copy:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version_number }}.linux-amd64/blackbox_exporter"
    dest: "/usr/local/bin/blackbox_exporter"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    remote_src: yes
    mode: 0755

- name: Delete Blackbox Exporter tmp folder
  file:
    path: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64"
    state: absent

- name: Creates directory
  file:
    path: "{{ blackbox_config_dir }}"
    state: directory
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    mode: 0755

- name: Copy Blackbox Exporter config file
  copy:
    src: blackbox_exporter.yml
    dest: "{{ blackbox_config_dir }}/blackbox.yml"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
  notify: restart_blackbox_exporter

- name: Copy systemd init file
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
  notify: systemd_reload

- name: Start Blackbox Exporter service
  service:
    name: blackbox_exporter
    state: started
    enabled: yes

- name: Check if Blackbox Exporter is accessible
  uri:
    url: http://localhost:9115
    method: GET
    status_code: 200
  retries: 3
  delay: 3
